/**
 * MiKloud - Customer Web API
 * This api is for the padelfy backend.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: dmartindiaz3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AreaInDTOHoursRangeInner } from './AreaInDTOHoursRangeInner';
import {
    AreaInDTOHoursRangeInnerFromJSON,
    AreaInDTOHoursRangeInnerFromJSONTyped,
    AreaInDTOHoursRangeInnerToJSON,
} from './AreaInDTOHoursRangeInner';

/**
 * 
 * @export
 * @interface AreaInDTO
 */
export interface AreaInDTO {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof AreaInDTO
     */
    facilityId: string;
    /**
     * 
     * @type {string}
     * @memberof AreaInDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AreaInDTO
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof AreaInDTO
     */
    img?: string;
    /**
     * 
     * @type {string}
     * @memberof AreaInDTO
     */
    color?: string;
    /**
     * 
     * @type {string}
     * @memberof AreaInDTO
     */
    icon?: string;
    /**
     * 
     * @type {string}
     * @memberof AreaInDTO
     */
    created?: string;
    /**
     * 
     * @type {Array<AreaInDTOHoursRangeInner>}
     * @memberof AreaInDTO
     */
    hoursRange: Array<AreaInDTOHoursRangeInner>;
}

/**
 * Check if a given object implements the AreaInDTO interface.
 */
export function instanceOfAreaInDTO(value: object): value is AreaInDTO {
    if (!('facilityId' in value) || value['facilityId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('hoursRange' in value) || value['hoursRange'] === undefined) return false;
    return true;
}

export function AreaInDTOFromJSON(json: any): AreaInDTO {
    return AreaInDTOFromJSONTyped(json, false);
}

export function AreaInDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AreaInDTO {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'facilityId': json['facilityId'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'img': json['img'] == null ? undefined : json['img'],
        'color': json['color'] == null ? undefined : json['color'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'created': json['created'] == null ? undefined : json['created'],
        'hoursRange': ((json['hoursRange'] as Array<any>).map(AreaInDTOHoursRangeInnerFromJSON)),
    };
}

export function AreaInDTOToJSON(value?: AreaInDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'facilityId': value['facilityId'],
        'name': value['name'],
        'description': value['description'],
        'img': value['img'],
        'color': value['color'],
        'icon': value['icon'],
        'created': value['created'],
        'hoursRange': ((value['hoursRange'] as Array<any>).map(AreaInDTOHoursRangeInnerToJSON)),
    };
}

