/* tslint:disable */
/* eslint-disable */
/**
 * MiKloud - Customer Web API
 * This api is for the padelfy backend.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: dmartindiaz3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AreaInDTOHoursRangeInner } from './AreaInDTOHoursRangeInner';
import {
    AreaInDTOHoursRangeInnerFromJSON,
    AreaInDTOHoursRangeInnerFromJSONTyped,
    AreaInDTOHoursRangeInnerToJSON,
} from './AreaInDTOHoursRangeInner';

/**
 * 
 * @export
 * @interface AreaOutDTO
 */
export interface AreaOutDTO {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof AreaOutDTO
     */
    facilityId?: string;
    /**
     * 
     * @type {string}
     * @memberof AreaOutDTO
     */
    areaId: string;
    /**
     * 
     * @type {string}
     * @memberof AreaOutDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AreaOutDTO
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof AreaOutDTO
     */
    img?: string;
    /**
     * 
     * @type {string}
     * @memberof AreaOutDTO
     */
    color?: string;
    /**
     * 
     * @type {string}
     * @memberof AreaOutDTO
     */
    icon?: string;
    /**
     * 
     * @type {string}
     * @memberof AreaOutDTO
     */
    created?: string;
    /**
     * 
     * @type {Array<AreaInDTOHoursRangeInner>}
     * @memberof AreaOutDTO
     */
    hoursRange: Array<AreaInDTOHoursRangeInner>;
}

/**
 * Check if a given object implements the AreaOutDTO interface.
 */
export function instanceOfAreaOutDTO(value: object): value is AreaOutDTO {
    if (!('areaId' in value) || value['areaId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('hoursRange' in value) || value['hoursRange'] === undefined) return false;
    return true;
}

export function AreaOutDTOFromJSON(json: any): AreaOutDTO {
    return AreaOutDTOFromJSONTyped(json, false);
}

export function AreaOutDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AreaOutDTO {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'facilityId': json['facilityId'] == null ? undefined : json['facilityId'],
        'areaId': json['areaId'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'img': json['img'] == null ? undefined : json['img'],
        'color': json['color'] == null ? undefined : json['color'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'created': json['created'] == null ? undefined : json['created'],
        'hoursRange': ((json['hoursRange'] as Array<any>).map(AreaInDTOHoursRangeInnerFromJSON)),
    };
}

export function AreaOutDTOToJSON(value?: AreaOutDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'facilityId': value['facilityId'],
        'areaId': value['areaId'],
        'name': value['name'],
        'description': value['description'],
        'img': value['img'],
        'color': value['color'],
        'icon': value['icon'],
        'created': value['created'],
        'hoursRange': ((value['hoursRange'] as Array<any>).map(AreaInDTOHoursRangeInnerToJSON)),
    };
}

