/* tslint:disable */
/* eslint-disable */
/**
 * MiKloud - Customer Web API
 * This api is for the padelfy backend.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: dmartindiaz3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookingInDTO
 */
export interface BookingInDTO {
    /**
     * 
     * @type {string}
     * @memberof BookingInDTO
     */
    areaId: string;
    /**
     * 
     * @type {string}
     * @memberof BookingInDTO
     */
    start: string;
    /**
     * 
     * @type {string}
     * @memberof BookingInDTO
     */
    end: string;
    /**
     * 
     * @type {number}
     * @memberof BookingInDTO
     */
    range: number;
    /**
     * 
     * @type {boolean}
     * @memberof BookingInDTO
     */
    pay?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BookingInDTO
     */
    online?: boolean;
}

/**
 * Check if a given object implements the BookingInDTO interface.
 */
export function instanceOfBookingInDTO(value: object): value is BookingInDTO {
    if (!('areaId' in value) || value['areaId'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    if (!('range' in value) || value['range'] === undefined) return false;
    return true;
}

export function BookingInDTOFromJSON(json: any): BookingInDTO {
    return BookingInDTOFromJSONTyped(json, false);
}

export function BookingInDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingInDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'areaId': json['areaId'],
        'start': json['start'],
        'end': json['end'],
        'range': json['range'],
        'pay': json['pay'] == null ? undefined : json['pay'],
        'online': json['online'] == null ? undefined : json['online'],
    };
}

export function BookingInDTOToJSON(value?: BookingInDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'areaId': value['areaId'],
        'start': value['start'],
        'end': value['end'],
        'range': value['range'],
        'pay': value['pay'],
        'online': value['online'],
    };
}

