/* tslint:disable */
/* eslint-disable */
/**
 * MiKloud - Customer Web API
 * This api is for the padelfy backend.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: dmartindiaz3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FacilityInDTO
 */
export interface FacilityInDTO {
    /**
     * 
     * @type {string}
     * @memberof FacilityInDTO
     */
    spaceId: string;
    /**
     * 
     * @type {string}
     * @memberof FacilityInDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof FacilityInDTO
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof FacilityInDTO
     */
    img?: string;
    /**
     * 
     * @type {string}
     * @memberof FacilityInDTO
     */
    color?: string;
    /**
     * 
     * @type {string}
     * @memberof FacilityInDTO
     */
    icon?: string;
    /**
     * 
     * @type {string}
     * @memberof FacilityInDTO
     */
    created?: string;
}

/**
 * Check if a given object implements the FacilityInDTO interface.
 */
export function instanceOfFacilityInDTO(value: object): value is FacilityInDTO {
    if (!('spaceId' in value) || value['spaceId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function FacilityInDTOFromJSON(json: any): FacilityInDTO {
    return FacilityInDTOFromJSONTyped(json, false);
}

export function FacilityInDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FacilityInDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'spaceId': json['spaceId'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'img': json['img'] == null ? undefined : json['img'],
        'color': json['color'] == null ? undefined : json['color'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'created': json['created'] == null ? undefined : json['created'],
    };
}

export function FacilityInDTOToJSON(value?: FacilityInDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'spaceId': value['spaceId'],
        'name': value['name'],
        'description': value['description'],
        'img': value['img'],
        'color': value['color'],
        'icon': value['icon'],
        'created': value['created'],
    };
}

