/* tslint:disable */
/* eslint-disable */
/**
 * MiKloud - Customer Web API
 * This api is for the padelfy backend.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: dmartindiaz3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationDTO } from './PaginationDTO';
import {
    PaginationDTOFromJSON,
    PaginationDTOFromJSONTyped,
    PaginationDTOToJSON,
} from './PaginationDTO';
import type { BookingOutDTO } from './BookingOutDTO';
import {
    BookingOutDTOFromJSON,
    BookingOutDTOFromJSONTyped,
    BookingOutDTOToJSON,
} from './BookingOutDTO';

/**
 * 
 * @export
 * @interface GetAreaBookings200Response
 */
export interface GetAreaBookings200Response {
    /**
     * 
     * @type {Array<BookingOutDTO>}
     * @memberof GetAreaBookings200Response
     */
    bookings?: Array<BookingOutDTO>;
    /**
     * 
     * @type {PaginationDTO}
     * @memberof GetAreaBookings200Response
     */
    pagination?: PaginationDTO;
}

/**
 * Check if a given object implements the GetAreaBookings200Response interface.
 */
export function instanceOfGetAreaBookings200Response(value: object): value is GetAreaBookings200Response {
    return true;
}

export function GetAreaBookings200ResponseFromJSON(json: any): GetAreaBookings200Response {
    return GetAreaBookings200ResponseFromJSONTyped(json, false);
}

export function GetAreaBookings200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAreaBookings200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'bookings': json['bookings'] == null ? undefined : ((json['bookings'] as Array<any>).map(BookingOutDTOFromJSON)),
        'pagination': json['pagination'] == null ? undefined : json['pagination'],
    };
}

export function GetAreaBookings200ResponseToJSON(value?: GetAreaBookings200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'bookings': value['bookings'] == null ? undefined : ((value['bookings'] as Array<any>).map(BookingOutDTOToJSON)),
        'pagination': value['pagination'],
    };
}

