/* tslint:disable */
/* eslint-disable */
/**
 * MiKloud - Customer Web API
 * This api is for the padelfy backend.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: dmartindiaz3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationDTO } from './PaginationDTO';
import {
    PaginationDTOFromJSON,
    PaginationDTOFromJSONTyped,
    PaginationDTOToJSON,
} from './PaginationDTO';
import type { AreaOutDTO } from './AreaOutDTO';
import {
    AreaOutDTOFromJSON,
    AreaOutDTOFromJSONTyped,
    AreaOutDTOToJSON,
} from './AreaOutDTO';

/**
 * 
 * @export
 * @interface GetFacilityAreas200Response
 */
export interface GetFacilityAreas200Response {
    /**
     * 
     * @type {Array<AreaOutDTO>}
     * @memberof GetFacilityAreas200Response
     */
    areas?: Array<AreaOutDTO>;
    /**
     * 
     * @type {PaginationDTO}
     * @memberof GetFacilityAreas200Response
     */
    pagination?: PaginationDTO;
}

/**
 * Check if a given object implements the GetFacilityAreas200Response interface.
 */
export function instanceOfGetFacilityAreas200Response(value: object): value is GetFacilityAreas200Response {
    return true;
}

export function GetFacilityAreas200ResponseFromJSON(json: any): GetFacilityAreas200Response {
    return GetFacilityAreas200ResponseFromJSONTyped(json, false);
}

export function GetFacilityAreas200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFacilityAreas200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'areas': json['areas'] == null ? undefined : ((json['areas'] as Array<any>).map(AreaOutDTOFromJSON)),
        'pagination': json['pagination'] == null ? undefined : json['pagination'],
    };
}

export function GetFacilityAreas200ResponseToJSON(value?: GetFacilityAreas200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'areas': value['areas'] == null ? undefined : ((value['areas'] as Array<any>).map(AreaOutDTOToJSON)),
        'pagination': value['pagination'],
    };
}

