/* tslint:disable */
/* eslint-disable */
/**
 * MiKloud - Customer Web API
 * This api is for the padelfy backend.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: dmartindiaz3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FacilityOutDTO } from './FacilityOutDTO';
import {
    FacilityOutDTOFromJSON,
    FacilityOutDTOFromJSONTyped,
    FacilityOutDTOToJSON,
} from './FacilityOutDTO';
import type { PaginationDTO } from './PaginationDTO';
import {
    PaginationDTOFromJSON,
    PaginationDTOFromJSONTyped,
    PaginationDTOToJSON,
} from './PaginationDTO';

/**
 * 
 * @export
 * @interface GetSpacesFacilities200Response
 */
export interface GetSpacesFacilities200Response {
    /**
     * 
     * @type {Array<FacilityOutDTO>}
     * @memberof GetSpacesFacilities200Response
     */
    facilities?: Array<FacilityOutDTO>;
    /**
     * 
     * @type {PaginationDTO}
     * @memberof GetSpacesFacilities200Response
     */
    pagination?: PaginationDTO;
}

/**
 * Check if a given object implements the GetSpacesFacilities200Response interface.
 */
export function instanceOfGetSpacesFacilities200Response(value: object): value is GetSpacesFacilities200Response {
    return true;
}

export function GetSpacesFacilities200ResponseFromJSON(json: any): GetSpacesFacilities200Response {
    return GetSpacesFacilities200ResponseFromJSONTyped(json, false);
}

export function GetSpacesFacilities200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSpacesFacilities200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'facilities': json['facilities'] == null ? undefined : ((json['facilities'] as Array<any>).map(FacilityOutDTOFromJSON)),
        'pagination': json['pagination'] == null ? undefined : json['pagination'],
    };
}

export function GetSpacesFacilities200ResponseToJSON(value?: GetSpacesFacilities200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'facilities': value['facilities'] == null ? undefined : ((value['facilities'] as Array<any>).map(FacilityOutDTOToJSON)),
        'pagination': value['pagination'],
    };
}

