/* tslint:disable */
/* eslint-disable */
/**
 * MiKloud - Customer Web API
 * This api is for the padelfy backend.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: dmartindiaz3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SpaceOutDTO } from './SpaceOutDTO';
import {
    SpaceOutDTOFromJSON,
    SpaceOutDTOFromJSONTyped,
    SpaceOutDTOToJSON,
} from './SpaceOutDTO';
import type { PaginationDTO } from './PaginationDTO';
import {
    PaginationDTOFromJSON,
    PaginationDTOFromJSONTyped,
    PaginationDTOToJSON,
} from './PaginationDTO';

/**
 * 
 * @export
 * @interface GetUserSpaces200Response
 */
export interface GetUserSpaces200Response {
    /**
     * 
     * @type {Array<SpaceOutDTO>}
     * @memberof GetUserSpaces200Response
     */
    spaces?: Array<SpaceOutDTO>;
    /**
     * 
     * @type {PaginationDTO}
     * @memberof GetUserSpaces200Response
     */
    pagination?: PaginationDTO;
}

/**
 * Check if a given object implements the GetUserSpaces200Response interface.
 */
export function instanceOfGetUserSpaces200Response(value: object): value is GetUserSpaces200Response {
    return true;
}

export function GetUserSpaces200ResponseFromJSON(json: any): GetUserSpaces200Response {
    return GetUserSpaces200ResponseFromJSONTyped(json, false);
}

export function GetUserSpaces200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserSpaces200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'spaces': json['spaces'] == null ? undefined : ((json['spaces'] as Array<any>).map(SpaceOutDTOFromJSON)),
        'pagination': json['pagination'] == null ? undefined : PaginationDTOFromJSON(json['pagination']),
    };
}

export function GetUserSpaces200ResponseToJSON(value?: GetUserSpaces200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'spaces': value['spaces'] == null ? undefined : ((value['spaces'] as Array<any>).map(SpaceOutDTOToJSON)),
        'pagination': PaginationDTOToJSON(value['pagination']),
    };
}

