/* tslint:disable */
/* eslint-disable */
/**
 * MiKloud - Customer Web API
 * This api is for the padelfy backend.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: dmartindiaz3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationInDTOUsersInner
 */
export interface NotificationInDTOUsersInner {
    /**
     * 
     * @type {string}
     * @memberof NotificationInDTOUsersInner
     */
    userId?: string;
}

/**
 * Check if a given object implements the NotificationInDTOUsersInner interface.
 */
export function instanceOfNotificationInDTOUsersInner(value: object): value is NotificationInDTOUsersInner {
    return true;
}

export function NotificationInDTOUsersInnerFromJSON(json: any): NotificationInDTOUsersInner {
    return NotificationInDTOUsersInnerFromJSONTyped(json, false);
}

export function NotificationInDTOUsersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationInDTOUsersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function NotificationInDTOUsersInnerToJSON(value?: NotificationInDTOUsersInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userId': value['userId'],
    };
}

