/* tslint:disable */
/* eslint-disable */
/**
 * MiKloud - Customer Web API
 * This api is for the padelfy backend.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: dmartindiaz3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginationDTO
 */
export interface PaginationDTO {
    /**
     * 
     * @type {number}
     * @memberof PaginationDTO
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationDTO
     */
    limitPerPage?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginationDTO
     */
    sort?: PaginationDTOSortEnum;
}


/**
 * @export
 */
export const PaginationDTOSortEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type PaginationDTOSortEnum = typeof PaginationDTOSortEnum[keyof typeof PaginationDTOSortEnum];


/**
 * Check if a given object implements the PaginationDTO interface.
 */
export function instanceOfPaginationDTO(value: object): value is PaginationDTO {
    if (!('page' in value) || value['page'] === undefined) return false;
    return true;
}

export function PaginationDTOFromJSON(json: any): PaginationDTO {
    return PaginationDTOFromJSONTyped(json, false);
}

export function PaginationDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'limitPerPage': json['limitPerPage'] == null ? undefined : json['limitPerPage'],
        'sort': json['sort'] == null ? undefined : json['sort'],
    };
}

export function PaginationDTOToJSON(value?: PaginationDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'page': value['page'],
        'limitPerPage': value['limitPerPage'],
        'sort': value['sort'],
    };
}

