/* tslint:disable */
/* eslint-disable */
/**
 * MiKloud - Customer Web API
 * This api is for the padelfy backend.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: dmartindiaz3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimpleUserOutDTO
 */
export interface SimpleUserOutDTO {
    /**
     * 
     * @type {string}
     * @memberof SimpleUserOutDTO
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof SimpleUserOutDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SimpleUserOutDTO
     */
    surname: string;
}

/**
 * Check if a given object implements the SimpleUserOutDTO interface.
 */
export function instanceOfSimpleUserOutDTO(value: object): value is SimpleUserOutDTO {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('surname' in value) || value['surname'] === undefined) return false;
    return true;
}

export function SimpleUserOutDTOFromJSON(json: any): SimpleUserOutDTO {
    return SimpleUserOutDTOFromJSONTyped(json, false);
}

export function SimpleUserOutDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleUserOutDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'name': json['name'],
        'surname': json['surname'],
    };
}

export function SimpleUserOutDTOToJSON(value?: SimpleUserOutDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userId': value['userId'],
        'name': value['name'],
        'surname': value['surname'],
    };
}

