/* tslint:disable */
/* eslint-disable */
/**
 * MiKloud - Customer Web API
 * This api is for the padelfy backend.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: dmartindiaz3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimpleUserInDTO
 */
export interface SimpleUserInDTO {
    /**
     * 
     * @type {string}
     * @memberof SimpleUserInDTO
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof SimpleUserInDTO
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof SimpleUserInDTO
     */
    password: string;
}

/**
 * Check if a given object implements the SimpleUserInDTO interface.
 */
export function instanceOfSimpleUserInDTO(value: object): value is SimpleUserInDTO {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function SimpleUserInDTOFromJSON(json: any): SimpleUserInDTO {
    return SimpleUserInDTOFromJSONTyped(json, false);
}

export function SimpleUserInDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleUserInDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'password': json['password'],
    };
}

export function SimpleUserInDTOToJSON(value?: SimpleUserInDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'phone': value['phone'],
        'password': value['password'],
    };
}

