/* tslint:disable */
/* eslint-disable */
/**
 * MiKloud - Customer Web API
 * This api is for the padelfy backend.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: dmartindiaz3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SpaceInDTOAddress } from './SpaceInDTOAddress';
import {
    SpaceInDTOAddressFromJSON,
    SpaceInDTOAddressFromJSONTyped,
    SpaceInDTOAddressToJSON,
} from './SpaceInDTOAddress';

/**
 * 
 * @export
 * @interface SpaceInDTO
 */
export interface SpaceInDTO {
    /**
     * 
     * @type {string}
     * @memberof SpaceInDTO
     */
    userId?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof SpaceInDTO
     */
    usersPermisions?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof SpaceInDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SpaceInDTO
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof SpaceInDTO
     */
    logo?: string;
    /**
     * 
     * @type {string}
     * @memberof SpaceInDTO
     */
    color?: string;
    /**
     * 
     * @type {SpaceInDTOAddress}
     * @memberof SpaceInDTO
     */
    address: SpaceInDTOAddress;
    /**
     * 
     * @type {string}
     * @memberof SpaceInDTO
     */
    created?: string;
}

/**
 * Check if a given object implements the SpaceInDTO interface.
 */
export function instanceOfSpaceInDTO(value: object): value is SpaceInDTO {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    return true;
}

export function SpaceInDTOFromJSON(json: any): SpaceInDTO {
    return SpaceInDTOFromJSONTyped(json, false);
}

export function SpaceInDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpaceInDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'usersPermisions': json['usersPermisions'] == null ? undefined : json['usersPermisions'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'logo': json['logo'] == null ? undefined : json['logo'],
        'color': json['color'] == null ? undefined : json['color'],
        'address': SpaceInDTOAddressFromJSON(json['address']),
        'created': json['created'] == null ? undefined : json['created'],
    };
}

export function SpaceInDTOToJSON(value?: SpaceInDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userId': value['userId'],
        'usersPermisions': value['usersPermisions'],
        'name': value['name'],
        'description': value['description'],
        'logo': value['logo'],
        'color': value['color'],
        'address': SpaceInDTOAddressToJSON(value['address']),
        'created': value['created'],
    };
}

