/* tslint:disable */
/* eslint-disable */
/**
 * MiKloud - Customer Web API
 * This api is for the padelfy backend.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: dmartindiaz3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserOutDTO
 */
export interface UserOutDTO {
    /**
     * 
     * @type {string}
     * @memberof UserOutDTO
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof UserOutDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UserOutDTO
     */
    surname: string;
    /**
     * 
     * @type {number}
     * @memberof UserOutDTO
     */
    phone?: number;
    /**
     * 
     * @type {number}
     * @memberof UserOutDTO
     */
    phonecode?: number;
    /**
     * 
     * @type {string}
     * @memberof UserOutDTO
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserOutDTO
     */
    created?: string;
    /**
     * 
     * @type {string}
     * @memberof UserOutDTO
     */
    lastConnect?: string;
    /**
     * 
     * @type {number}
     * @memberof UserOutDTO
     */
    age?: number;
    /**
     * 
     * @type {string}
     * @memberof UserOutDTO
     */
    role: string;
}

/**
 * Check if a given object implements the UserOutDTO interface.
 */
export function instanceOfUserOutDTO(value: object): value is UserOutDTO {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('surname' in value) || value['surname'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function UserOutDTOFromJSON(json: any): UserOutDTO {
    return UserOutDTOFromJSONTyped(json, false);
}

export function UserOutDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserOutDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'name': json['name'],
        'surname': json['surname'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'phonecode': json['phonecode'] == null ? undefined : json['phonecode'],
        'email': json['email'],
        'created': json['created'] == null ? undefined : json['created'],
        'lastConnect': json['lastConnect'] == null ? undefined : json['lastConnect'],
        'age': json['age'] == null ? undefined : json['age'],
        'role': json['role'],
    };
}

export function UserOutDTOToJSON(value?: UserOutDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userId': value['userId'],
        'name': value['name'],
        'surname': value['surname'],
        'phone': value['phone'],
        'phonecode': value['phonecode'],
        'email': value['email'],
        'created': value['created'],
        'lastConnect': value['lastConnect'],
        'age': value['age'],
        'role': value['role'],
    };
}

